title: Time of Kairos
description: "안병현의 블로그"
baseurl: ""
url: "https://abh0518.github.io"
permalink: /:year/:month/:day/:title/
markdown: kramdown
encoding: utf-8

lang: ko-KR

remote_theme: "cotes2020/jekyll-theme-chirpy@v5.6.1"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives

# 사이트 저자 정보
author:
  name: "안병현"
  email: abh0518@gmail.com
  url: "https://abh0518.github.io"

# Chirpy 테마 설정
theme_mode: # light / dark (비워두면 시스템 설정 따름)

avatar: /assets/images/2026/04/profile.jpg

toc: true

# 검색
search:
  full_content: true

# 소셜 링크 (필요시 설정)
social:
  name: 안병현
  email: abh0518@gmail.com
  links:
    - https://github.com/abh0518

# 페이지네이션
paginate: 10

# jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

collections:
  tabs:
    output: true
    sort_by: order

exclude:
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_date: true
      read_time: true
      words_per_minute: 200
      share: true
      related: true
      toc: true
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
